tap "dart-lang/dart"
tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "cocoapods"
brew "fzf"
brew "git"
brew "go"
brew "htop"
brew "usbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "ios-deploy"
brew "jq"
brew "leiningen"
brew "neovim"
brew "p7zip"
brew "postgresql", restart_service: true
brew "screenfetch"
brew "the_silver_searcher"
brew "tig"
brew "unrar"
brew "wget"
brew "zsh"
brew "dart-lang/dart/dart"
brew "getantibody/tap/antibody"
cask "java"
cask "spotify"
cask "visual-studio-code"
