tap "dart-lang/dart"
tap "getantibody/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "leoafarias/fvm"
tap "miderwong/flutter"
brew "ack"
brew "broot"
brew "coreutils"
brew "docker", link: false
brew "fzf"
brew "git"
brew "go"
brew "golang-migrate"
brew "graphicsmagick"
brew "htop"
brew "libusbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "imagemagick"
brew "jq"
brew "leiningen"
brew "librsvg"
brew "libxml2"
brew "neovim"
brew "oath-toolkit"
brew "pgcli"
brew "pidcat"
brew "postgresql", restart_service: true
brew "redis", restart_service: true
brew "screenfetch"
brew "skaffold"
brew "sqlc"
brew "the_silver_searcher"
brew "tig"
brew "tldr"
brew "tmux"
brew "unrar"
brew "watchexec"
brew "wget"
brew "zsh"
brew "antidote"
brew "leoafarias/fvm/fvm"
cask "docker"
cask "font-iosevka"
cask "font-iosevka-slab"
cask "postman"
cask "spotify"
cask "visual-studio-code"
